export const DIMENSIONS = [
  {
    code: "grit_perseverance",
    nameKey: "dimensions.grit_perseverance",
    category: "ENTREPRENEURIAL" as const,
    startupWeight: 0.15,
    generalWeight: 0.10,
    description: "Grit & Perseverance (Consistency of Interest + Perseverance of Effort)",
    sortOrder: 1,
    subScores: [
      { code: "grit_consistency", label: "Consistency of Interest", weightKey: "grit_consistency" },
      { code: "grit_effort", label: "Perseverance of Effort", weightKey: "grit_effort" },
    ],
  },
  {
    code: "risk_tolerance",
    nameKey: "dimensions.risk_tolerance",
    category: "ENTREPRENEURIAL" as const,
    startupWeight: 0.13,
    generalWeight: 0.07,
    description: "Risk Tolerance & Uncertainty Management",
    sortOrder: 2,
  },
  {
    code: "proactivity",
    nameKey: "dimensions.proactivity",
    category: "ENTREPRENEURIAL" as const,
    startupWeight: 0.12,
    generalWeight: 0.10,
    description: "Proactivity & Initiative",
    sortOrder: 3,
  },
  {
    code: "eq_self_regulation",
    nameKey: "dimensions.eq_self_regulation",
    category: "PERSONALITY" as const,
    startupWeight: 0.09,
    generalWeight: 0.12,
    description: "EQ & Self-Regulation",
    sortOrder: 4,
  },
  {
    code: "growth_mindset",
    nameKey: "dimensions.growth_mindset",
    category: "COGNITIVE" as const,
    startupWeight: 0.08,
    generalWeight: 0.10,
    description: "Growth Mindset & Learning Agility",
    sortOrder: 5,
  },
  {
    code: "integrity",
    nameKey: "dimensions.integrity",
    category: "PERSONALITY" as const,
    startupWeight: 0.08,
    generalWeight: 0.11,
    description: "Integrity & Values Alignment",
    sortOrder: 6,
  },
  {
    code: "strategic_thinking",
    nameKey: "dimensions.strategic_thinking",
    category: "COGNITIVE" as const,
    startupWeight: 0.09,
    generalWeight: 0.08,
    description: "Strategic Thinking & Vision",
    sortOrder: 7,
  },
  {
    code: "collaboration",
    nameKey: "dimensions.collaboration",
    category: "INTERPERSONAL" as const,
    startupWeight: 0.06,
    generalWeight: 0.10,
    description: "Collaboration & Interpersonal",
    sortOrder: 8,
  },
  {
    code: "self_efficacy",
    nameKey: "dimensions.self_efficacy",
    category: "PERSONALITY" as const,
    startupWeight: 0.08,
    generalWeight: 0.08,
    description: "Self-Efficacy, Ownership & Locus of Control",
    sortOrder: 9,
  },
  {
    code: "innovativeness",
    nameKey: "dimensions.innovativeness",
    category: "COGNITIVE" as const,
    startupWeight: 0.06,
    generalWeight: 0.06,
    description: "Innovativeness & Problem-Solving",
    sortOrder: 10,
  },
  {
    code: "action_orientation",
    nameKey: "dimensions.action_orientation",
    category: "ENTREPRENEURIAL" as const,
    startupWeight: 0.04,
    generalWeight: 0.05,
    description: "Action Orientation & Execution",
    sortOrder: 11,
  },
  {
    code: "physical_mental_vitality",
    nameKey: "dimensions.physical_mental_vitality",
    category: "PERSONALITY" as const,
    startupWeight: 0.02,
    generalWeight: 0.03,
    description: "Physical & Mental Vitality",
    sortOrder: 12,
  },
] as const;

export const TIER_THRESHOLDS = {
  STARTUP_COFOUNDER: {
    READY_TO_LEAD: { min: 85, label: "Ready to Lead" },
    READY_TO_BUILD: { min: 65, label: "Ready to Build" },
    READY_TO_CONTRIBUTE: { min: 45, label: "Ready to Contribute" },
    GROWING_FOUNDATION: { min: 0, label: "Growing Foundation" },
  },
  STRUCTURED_TECH: {
    READY_TO_LEAD: { min: 80, label: "Ready to Lead" },
    READY_TO_BUILD: { min: 60, label: "Ready to Build" },
    READY_TO_CONTRIBUTE: { min: 40, label: "Ready to Contribute" },
    GROWING_FOUNDATION: { min: 0, label: "Growing Foundation" },
  },
  INDEPENDENT_CONSULTANT: {
    READY_TO_LEAD: { min: 85, label: "Ready to Lead" },
    READY_TO_BUILD: { min: 65, label: "Ready to Build" },
    READY_TO_CONTRIBUTE: { min: 45, label: "Ready to Contribute" },
    GROWING_FOUNDATION: { min: 0, label: "Growing Foundation" },
  },
  TEAM_AMTARIKSHA: {
    READY_TO_LEAD: { min: 80, label: "Ready to Lead" },
    READY_TO_BUILD: { min: 60, label: "Ready to Build" },
    READY_TO_CONTRIBUTE: { min: 40, label: "Ready to Contribute" },
    GROWING_FOUNDATION: { min: 0, label: "Growing Foundation" },
  },
} as const;

export const ASSESSMENT_CONFIG = {
  MIN_SJT_QUESTIONS: 12,
  MAX_SJT_QUESTIONS: 15,
  MIN_QUESTIONS_PER_DIMENSION: 1,
  MAX_QUESTIONS_PER_DIMENSION: 2,
  SJT_TIME_LIMIT_SECONDS: 90,
  FREETEXT_TIME_LIMIT_SECONDS: 120,
  SJT_SCORE_WEIGHT: 0.6,
  AI_SCORE_WEIGHT: 0.4,
  MIN_RESPONSE_TIME_MS: 3000,
  MAX_RESPONSE_TIME_MS: 300000,
  COMMITMENT_FLAG_THRESHOLDS: {
    highIntegrity: 70,
    highVision: 70,
    highRisk: 60,
    lowGritPerseverance: 40,
    lowAction: 40,
  },
} as const;

export const SUPPORTED_LOCALES = ["en", "hi"] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const LOCALE_LABELS: Record<SupportedLocale, string> = {
  en: "English",
  hi: "हिन्दी",
};
